<br><br>
<div class="admin__page-section-title head-account">
    <span class="title">Forter Client Web ID <span style="font-size: 70%">* enter number without spaces</span></span>
    <div class="actions"></div>
</div>
<div class="admin__field field">
    <label class="label admin__field-label" for="order-forter_web_id" ><span>Client number to track</span></label>
    <div class="admin__field-control control">
      <input id="forter_web_id" name="forter_web_id" value="" class="maximum-length-255 minimum-length-1 validate-length input-text admin__control-text" type="text" style="width: 60%;">
    </div>
</div>
