<?php
/**
 * @var Eset\License\Block\Adminhtml\Order\View\Tab\Invoice $block
 */
$adminOrder = false;
$data = $block->getForterEntity() ?? $block->getOrder();
$forterResponse = $data->getData('forter_response');

if ($forterResponse):
    $forterResponse = is_null($forterResponse) ? [] : json_decode($forterResponse);
    ?>

    <section class="admin__page-section">
        <div class="admin__page-section-title invoice_title">
            <span class="title"><?php echo $block->escapeHtml(__("Forter Response Details")); ?></span>
        </div>
    </section>

    <?php if (isset($forterResponse->status)): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-content">
            <div class="admin__page-section-item-title invoice_item_title">
                <span class="title"><?php echo $block->escapeHtml(__("Forter API Request Status")); ?></span>
            </div>
            <div class="admin__page-section-item-content invoice_item_content">
                <div class=""><?php echo $block->escapeHtml($forterResponse->status); ?></div>
            </div>
        </div>
    </section>
<?php endif; ?>

    <?php if (isset($forterResponse->action)): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-content">
            <div class="admin__page-section-item-title invoice_item_title">
                <span class="title"><?php echo $block->escapeHtml(__("Forter Action (Decision)")); ?></span>
            </div>
            <div class="admin__page-section-item-content invoice_item_content">
                <div class=""><?php echo $block->escapeHtml($forterResponse->action); ?></div>
            </div>
        </div>
    </section>
<?php endif; ?>

    <?php if (!empty($forterResponse->recommendations) && is_array($forterResponse->recommendations)): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-content">
            <div class="admin__page-section-item-title invoice_item_title">
                <span class="title"><?php echo $block->escapeHtml(__("Forter Recommendations")); ?></span>
            </div>
            <div class="admin__page-section-item-content invoice_item_content">
                <?php foreach ($forterResponse->recommendations as $recommendation): ?>
                    <?php if ($recommendation && is_string($recommendation)): ?>
                        <div><?php echo $block->escapeHtml( $block->getRecommendationMessageByKey($recommendation) ); ?>
                            (<?php echo $block->escapeHtml($recommendation); ?>)
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </section>
<?php endif; ?>

    <?php if (isset($forterResponse->message)): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-content">
            <div class="admin__page-section-item-title invoice_item_title">
                <span class="title"><?php echo $block->escapeHtml(__("Forter Message")); ?></span>
            </div>
            <div class="admin__page-section-item-content invoice_item_content">
                <div class=""><?php echo $block->escapeHtml($forterResponse->message); ?></div>
            </div>
        </div>
    </section>
<?php endif; ?>

    <?php if (isset($forterResponse->reasonCode)): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-content">
            <div class="admin__page-section-item-title invoice_item_title">
                <span class="title"><?php echo $block->escapeHtml(__("Forter Reason Code")); ?></span>
            </div>
            <div class="admin__page-section-item-content invoice_item_content">
                <div class=""><?php echo $block->escapeHtml($forterResponse->reasonCode); ?></div>
            </div>
        </div>
    </section>
<?php endif; ?>

    <?php if (isset($forterResponse->reason)): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-content">
            <div class="admin__page-section-item-title invoice_item_title">
                <span class="title"><?php echo $block->escapeHtml(__("Forter Reason Code")); ?></span>
            </div>
            <div class="admin__page-section-item-content invoice_item_content">
                <div class=""><?php echo $block->escapeHtml($forterResponse->reason); ?></div>
            </div>
        </div>
    </section>
<?php endif; ?>

    <?php if (isset($forterResponse->errors)): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-content">
            <div class="admin__page-section-item-title invoice_item_title">
                <span class="title"><?php echo $block->escapeHtml(__("Forter Errors")); ?></span>
            </div>
            <?php foreach ($forterResponse->errors as $element): ?>
                <div class="admin__page-section-item-content invoice_item_content">
                    <div class=""><strong
                            style="color:red;"><?php echo $block->escapeHtml(__("Error Path: ")); ?></strong><?php echo $block->escapeHtml(stripcslashes(json_encode($element->path))); ?>
                    </div>
                    <div class=""><strong
                            style="color:red;"><?php echo $block->escapeHtml(__("Error Message: ")); ?></strong><?php echo $block->escapeHtml(json_encode($element->message)); ?>
                    </div>
                    <br><br>
                </div>
            <?php endforeach; ?>
        </div>
    </section>
<?php endif; ?>
<?php endif; ?>
