<?php
/**
 * @var Eset\License\Block\Adminhtml\Order\View\Tab\Invoice $block
*/
$adminOrder = false;
$order = $this->getOrder();
$forterResponse = $order->getData('forter_response');
$forterResponse = json_decode($forterResponse);
$isEnabled = $block->isEnabled();
//check order was made from admin site
if (empty($order->getRemoteIp()) == true ) {
    $adminOrder = true;
    $clientNumber = $order->getForterWebId();
}
?>
<?php if($adminOrder == true && $isEnabled == true): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title invoice_title">
            <span class="title"><?php echo __("Client number to track"); ?></span>
            <br><br><label for="forter_web_id" class="admin__field-label"><?php echo $clientNumber;?></label><br><br>
        </div>
    </section>
<?php endif; ?>

<section class="admin__page-section">
    <div class="admin__page-section-title invoice_title">
        <span class="title"><?php echo __("Forter Response Details"); ?></span>
    </div>
</section>

<?php if (isset($forterResponse->status)): ?>
<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item-title invoice_item_title">
            <span class="title"><?php echo __("Forter API Request Status"); ?></span>
        </div>
        <div class="admin__page-section-item-content invoice_item_content">
            <div class=""><?php echo $forterResponse->status; ?></div>
        </div>
    </div>
</section>
<?php endif; ?>

<?php if (isset($forterResponse->action)): ?>
<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item-title invoice_item_title">
            <span class="title"><?php echo __("Forter Action (Decision)"); ?></span>
        </div>
        <div class="admin__page-section-item-content invoice_item_content">
            <div class=""><?php echo $forterResponse->action;?></div>
        </div>
    </div>
</section>
<?php endif; ?>

<?php if (isset($forterResponse->message)): ?>
<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item-title invoice_item_title">
            <span class="title"><?php echo __("Forter Message"); ?></span>
        </div>
        <div class="admin__page-section-item-content invoice_item_content">
            <div class=""><?php echo $forterResponse->message;?></div>
        </div>
    </div>
</section>
<?php endif; ?>

<?php if (isset($forterResponse->reasonCode)): ?>
<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item-title invoice_item_title">
            <span class="title"><?php echo __("Forter Reason Code"); ?></span>
        </div>
        <div class="admin__page-section-item-content invoice_item_content">
            <div class=""><?php echo $forterResponse->reasonCode;?></div>
        </div>
    </div>
</section>
<?php endif; ?>

<?php if (isset($forterResponse->errors)): ?>
<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item-title invoice_item_title">
            <span class="title"><?php echo __("Forter Errors"); ?></span>
        </div>
        <?php foreach ($forterResponse->errors as $element): ?>
        <div class="admin__page-section-item-content invoice_item_content">
            <div class=""><strong style="color:red;"><?php echo __("Error Path: "); ?></strong><?php echo stripcslashes(json_encode($element->path)); ?></div>
            <div class=""><strong style="color:red;"><?php echo __("Error Message: "); ?></strong><?php echo json_encode($element->message); ?></div><br><br>
        </div>
        <?php endforeach; ?>
    </div>
</section>
<?php endif; ?>
