<?php

if($block->getData('span-title')) {
    $title = $block->getData('span-title');
}
?>

<div class="forter_webId" style="color: <?php echo $block->getData('color-1'); ?>; font-family: <?php echo $block->getData('font-1'); ?>;">
    <span><?php echo $title; ?></span>
    <span class="forter_code" style="color: <?php echo $block->getData('color-2'); ?>; font-family: <?php echo $block->getData('font-2'); ?>"></span>
</div>